on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - run: |
          echo "::group::test group"
          echo "testing"
          exit 1
          echo "::endgroup::"
      - uses: actions/checkout@v4
      - id: foo
        uses: austinletson/action-failure-log-group-test@main
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
